### PR TITLE
Retrieve data from S3 instead of https

### PR DESCRIPTION
**Pull request by ghost**
As of the new version 2.0.0, {arrow} supports loading parquet files from S3. This PR updates `get_performance_tiles` to use that, which removes the dependency on {httr} (and downloads slightly faster from my experience!).

I also ran `styler::style_pkg()` to apply uniform code formatting to all files.

### CODE REVIEW

**Comment by katiejolly-ookla** [comment]
quick! I was about to ask if the new release would make things easier here.

**Review by smpetersen — APPROVED** [review]
Great upgrade!

**Comment by bdcookla** [comment]
one downside: there isn't a progress bar when the file is downloading. does it seem like a good idea to print a message that the file is downloading so that people don't think R has locked up?

**Comment by katiejolly-ookla** [comment]
I like that idea! It takes a little while so it's easy to think R is frozen in the meantime.

**Comment by katiejolly-ookla** [comment]
I'll take a look at these changes later tonight or tomorrow.

**Review by katiejolly-ookla — APPROVED** [review]

**Pull request merged**
